baseURL = 'localhost:1313'
languageCode = 'en-us'
title = 'Nadav Kempinski'
theme = 'cupper-hugo-theme'

[Params]
    me_img_path = '/me.png'
    intro = "I’m a 20-something working at the intersection of people and soil to develop nature-based solutions for the climate crisis. I aim to use design to make sustainable choices seamless for industry and consumers."
    values = "Lifelong learner, curiosity-driven, and described as a 'minimalist maximalist.' You'll understand once you get to know me."
    learnMore = "Check out my [LinkedIn](https://linkedin.com/in/nadav-kempinski), [personal Substack](https://nadav.substack.com), or [send me an email](mailto:nadavkempinski+web@gmail.com)."
